#!/usr/bin/env python3
"""Point the three Python wrappers at a published Lattice Grid release.

One command does everything a grid bump needs, so no version is ever typed by
hand and no two files can disagree:

    python tools/bump_grid.py --grid-version 1.69.0

It fetches that exact version's npm tarball, reads the grid version out of the
tarball's own ``package.json`` (the tarball is the authority -- the argument is
only a request), vendors the browser bundle into the wheels that ship it, and
rewrites every version string in the repository:

* ``lattice_grid_pandas/grid_bundle.json`` -- the generated record of which grid
  is vendored. ``lattice_grid_pandas.GRID_VERSION`` reads it at import, so no
  Python source carries a grid version at all.
* the three ``pyproject.toml`` versions and the ``lattice-grid-pandas==`` pins
  the two host wrappers carry, so the trio stays installable in lockstep.
* the two ``__version__`` strings, the Dash component's three JSON files, and
  the grid version quoted in the READMEs.

The wrapper version is the grid version plus a revision component --
``1.69.0`` -> ``1.69.0.0`` -- so a reader can tell which grid a wheel carries
from its number alone, and a second wheel for the same grid (a packaging fix)
can go out as ``1.69.0.1`` via ``--revision 1``.

The Dash component's browser bundle has the grid compiled into it, so it must be
rebuilt after this runs:

    cd packages/lattice-grid-dash && npm install && npm run build:js

``--build-dash`` does that for you when Node is on the path.
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import shutil
import subprocess
import sys
import tarfile
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
NPM_PACKAGE = "@toclocoinc/lattice-grid"

_SEMVER = re.compile(r"^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$")


def _log(message: str) -> None:
    """Print one progress line, flushed so CI logs stay in order."""
    print(f"[bump_grid] {message}", flush=True)


def fetch_tarball(version: str, into: pathlib.Path) -> pathlib.Path:
    """``npm pack`` the requested grid version and unpack it. Returns the package dir."""
    into.mkdir(parents=True, exist_ok=True)
    spec = f"{NPM_PACKAGE}@{version}"
    _log(f"npm pack {spec}")
    result = subprocess.run(
        ["npm", "pack", spec, "--pack-destination", str(into)],
        check=True, capture_output=True, text=True,
    )
    name = result.stdout.strip().splitlines()[-1]
    tgz = into / name
    if not tgz.exists():
        raise SystemExit(f"npm pack reported {name}, but {tgz} is not there")
    _log(f"unpacking {tgz.name} ({tgz.stat().st_size:,} bytes)")
    with tarfile.open(tgz) as tar:
        tar.extractall(into)
    package = into / "package"
    if not (package / "package.json").exists():
        raise SystemExit(f"{tgz.name} has no package/package.json")
    return package


def grid_version_of(package: pathlib.Path) -> str:
    """The version the tarball declares -- the one authority on what was fetched."""
    meta = json.loads((package / "package.json").read_text(encoding="utf-8"))
    version = str(meta.get("version", ""))
    if not _SEMVER.match(version):
        raise SystemExit(f"tarball declares an unusable version: {version!r}")
    return version


def vendor_bundle(package: pathlib.Path) -> list[pathlib.Path]:
    """Copy the grid's browser bundle into every wrapper that ships it offline."""
    js = package / "lattice-grid.min.js"
    css = package / "lattice-grid.min.css"
    for src in (js, css):
        if not src.exists():
            raise SystemExit(f"the tarball is missing {src.name}; nothing to vendor")
    targets = [
        (js, ROOT / "src/lattice_grid_jupyter/static/lattice-grid.min.js"),
        (css, ROOT / "src/lattice_grid_jupyter/static/lattice-grid.min.css"),
        # The Dash component compiles the grid into its own bundle (build.mjs), so
        # only the stylesheet is copied here; `npm run build:js` does the rest.
        (css, ROOT / "packages/lattice-grid-dash/lattice_grid_dash/lattice-grid.min.css"),
    ]
    written = []
    for src, dest in targets:
        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, dest)
        written.append(dest)
        _log(f"vendored {dest.relative_to(ROOT)} ({dest.stat().st_size:,} bytes)")
    return written


def write_grid_bundle_json(grid_version: str) -> pathlib.Path:
    """Record the vendored grid version where ``lattice_grid_pandas`` reads it."""
    path = ROOT / "packages/lattice-grid-pandas/src/lattice_grid_pandas/grid_bundle.json"
    path.write_text(
        json.dumps(
            {
                "_comment": "Generated by tools/bump_grid.py from the npm tarball. Do not edit.",
                "npm_package": NPM_PACKAGE,
                "grid_version": grid_version,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    _log(f"wrote {path.relative_to(ROOT)} -> {grid_version}")
    return path


def _sub_once(path: pathlib.Path, pattern: str, replacement: str) -> None:
    """Replace exactly one match, or stop. A silent miss is how versions drift."""
    text = path.read_text(encoding="utf-8")
    new_text, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise SystemExit(f"{path.relative_to(ROOT)}: pattern {pattern!r} matched {count} times, wanted 1")
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")


def _sub_all(path: pathlib.Path, pattern: str, replacement: str, least: int = 1) -> int:
    """Replace every match; stop if fewer than ``least`` were found."""
    text = path.read_text(encoding="utf-8")
    new_text, count = re.subn(pattern, replacement, text, flags=re.MULTILINE)
    if count < least:
        raise SystemExit(f"{path.relative_to(ROOT)}: pattern {pattern!r} matched {count} times, wanted >= {least}")
    if new_text != text:
        path.write_text(new_text, encoding="utf-8")
    return count


def rewrite_versions(grid_version: str, wrapper_version: str) -> None:
    """Put ``wrapper_version`` on all three packages and ``grid_version`` on the pins."""
    ver = r'^version = "[^"]+"$'
    for rel in (
        "pyproject.toml",
        "packages/lattice-grid-pandas/pyproject.toml",
        "packages/lattice-grid-dash/pyproject.toml",
    ):
        _sub_once(ROOT / rel, ver, f'version = "{wrapper_version}"')

    # The two host wrappers pin the shared package exactly, so a mixed install is
    # impossible: pip refuses rather than quietly pairing new with old.
    pin = r'"lattice-grid-pandas==[^"]+"'
    for rel in ("pyproject.toml", "packages/lattice-grid-dash/pyproject.toml"):
        _sub_once(ROOT / rel, pin, f'"lattice-grid-pandas=={wrapper_version}"')

    dunder = r'^__version__ = "[^"]+"$'
    for rel in (
        "src/lattice_grid_jupyter/__init__.py",
        "packages/lattice-grid-pandas/src/lattice_grid_pandas/__init__.py",
    ):
        _sub_once(ROOT / rel, dunder, f'__version__ = "{wrapper_version}"')

    # The Dash component's JSON: its own version, and the grid it builds against.
    for rel in (
        "packages/lattice-grid-dash/package.json",
        "packages/lattice-grid-dash/package-info.json",
        "packages/lattice-grid-dash/lattice_grid_dash/package-info.json",
    ):
        _sub_once(ROOT / rel, r'"version": "[^"]+"', f'"version": "{wrapper_version}"')
    for rel in (
        "packages/lattice-grid-dash/package.json",
        "packages/lattice-grid-dash/lattice_grid_dash/package-info.json",
    ):
        _sub_once(
            ROOT / rel,
            r'"@toclocoinc/lattice-grid": "[^"]+"',
            f'"@toclocoinc/lattice-grid": "{grid_version}"',
        )

    # Documentation quotes the grid version too; a doc that lies is a doc that
    # sends someone to the wrong CDN URL.
    _sub_all(ROOT / "README.md", r"@toclocoinc/lattice-grid@\d+\.\d+\.\d+", f"@toclocoinc/lattice-grid@{grid_version}")
    _sub_all(ROOT / "packages/lattice-grid-dash/README.md", r"grid v\d+\.\d+\.\d+", f"grid v{grid_version}")
    _log(f"rewrote versions -> wrapper {wrapper_version}, grid {grid_version}")


def build_dash(grid_version: str) -> None:
    """Rebuild the Dash browser bundle so it carries the new grid."""
    where = ROOT / "packages/lattice-grid-dash"
    _log(f"npm install in {where.relative_to(ROOT)}")
    subprocess.run(["npm", "install"], cwd=where, check=True)
    _log("npm run build:js")
    subprocess.run(["npm", "run", "build:js"], cwd=where, check=True)
    bundle = where / "lattice_grid_dash/lattice_grid_dash.min.js"
    stamp = f"Lattice Grid {grid_version}"
    if stamp not in bundle.read_text(encoding="utf-8", errors="replace"):
        raise SystemExit(
            f"{bundle.name} was rebuilt but does not carry '{stamp}'; "
            "the esbuild run picked up a different grid."
        )
    _log(f"built {bundle.relative_to(ROOT)} ({bundle.stat().st_size:,} bytes), carries {stamp}")


def main(argv: list[str] | None = None) -> int:
    """Parse the arguments and run the bump end to end."""
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--grid-version", required=True, help="the published grid version, e.g. 1.69.0")
    parser.add_argument("--revision", default="0", help="the wrapper revision suffix (default 0)")
    parser.add_argument("--tarball-dir", default=None, help="keep the unpacked tarball here instead of a temp dir")
    parser.add_argument("--build-dash", action="store_true", help="also rebuild the Dash browser bundle (needs Node)")
    args = parser.parse_args(argv)

    if not _SEMVER.match(args.grid_version):
        raise SystemExit(f"--grid-version {args.grid_version!r} is not a version")
    if not re.match(r"^\d+$", args.revision):
        raise SystemExit(f"--revision {args.revision!r} must be a number")

    with tempfile.TemporaryDirectory() as tmp:
        into = pathlib.Path(args.tarball_dir) if args.tarball_dir else pathlib.Path(tmp)
        package = fetch_tarball(args.grid_version, into)
        grid_version = grid_version_of(package)
        if grid_version != args.grid_version:
            raise SystemExit(
                f"asked npm for {args.grid_version} and got a tarball declaring {grid_version}"
            )
        wrapper_version = f"{grid_version}.{args.revision}"
        vendor_bundle(package)
        write_grid_bundle_json(grid_version)
        rewrite_versions(grid_version, wrapper_version)

    if args.build_dash:
        build_dash(grid_version)

    print(f"GRID_VERSION={grid_version}")
    print(f"WRAPPER_VERSION={wrapper_version}")
    out = os.environ.get("GITHUB_OUTPUT")
    if out:
        with open(out, "a", encoding="utf-8") as fh:
            fh.write(f"grid_version={grid_version}\n")
            fh.write(f"wrapper_version={wrapper_version}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
