#!/usr/bin/env python3
"""Regenerate ``src/lattice_grid_jupyter/_chart_names.py`` from the grid's own types.

    python tools/gen_chart_names.py path/to/lattice-grid.d.ts

The chart module does not report an unknown spec key, so ``LatticeChart`` does it
here, by name, against the property names the grid's ``ChartSpec`` declares (the
extension chart types' own keys are listed by hand in ``_chart.py``).
``tools/bump_grid.py`` runs it on every grid bump.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "lattice_grid_jupyter" / "_chart_names.py"


def main(dts: str) -> int:
    text = pathlib.Path(dts).read_text(encoding="utf-8")
    body = re.search(r"^export interface ChartSpec \{\n(.*?)^\}", text, re.M | re.S).group(1)
    keys = sorted(set(re.findall(r"^  (?:readonly )?([A-Za-z][A-Za-z0-9]*)\??:", body, re.M)))
    types = re.search(r"^export type ChartType =\n(.*?);", text, re.M | re.S).group(1)
    chart_types = sorted(set(re.findall(r"'([A-Za-z]+)'", types)))
    version = json.loads((pathlib.Path(dts).parent / "package.json").read_text())["version"]
    lines = ['"""GENERATED by tools/gen_chart_names.py from the grid declarations. Do not edit."""', "",
             f'GRID_VERSION = "{version}"', "", "# every property the grid's ChartSpec declares", "SPEC_KEYS = frozenset({"]
    lines += [f'    "{k}",' for k in keys] + ["})", "", "# the built-in ChartType names", "CORE_TYPES = frozenset({"]
    lines += [f'    "{t}",' for t in chart_types] + ["})", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(keys)} ChartSpec keys, {len(chart_types)} chart types from grid {version} -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
