#!/usr/bin/env python3
"""Regenerate ``src/lattice_grid_jupyter/_option_names.py`` from the grid's own types.

    python tools/gen_option_names.py path/to/lattice-grid.d.ts

The widget maps ``snake_case`` option keys to camelCase, but only for keys whose
camelCase form is a real grid property name, so a user's own ids (a column called
``sales_total``) are never rewritten. The names come from the shipped declarations.
Run it as part of a grid bump, then ``tools/check_grid_pin.py``.
"""
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "lattice_grid_jupyter" / "_option_names.py"


def main(dts: str) -> int:
    text = pathlib.Path(dts).read_text(encoding="utf-8")
    names = set(re.findall(r"^ {2,}(?:readonly )?([a-z][A-Za-z0-9]*)\??\s*[:(<]", text, re.M))
    camel = sorted(n for n in names if re.search(r"[A-Z]", n))
    version_dir = pathlib.Path(dts).parent / "package.json"
    import json
    version = json.loads(version_dir.read_text())["version"]
    lines = [
        '"""GENERATED by tools/gen_option_names.py from the grid declarations. Do not edit."""',
        "",
        f'GRID_VERSION = "{version}"',
        "",
        "# every camelCase property name the grid's types declare",
        "CAMEL_NAMES = frozenset({",
    ]
    lines += [f'    "{n}",' for n in camel]
    lines += ["})", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"{len(camel)} camelCase names from grid {version} -> {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1]))
